# Generated by Django 2.0.3 on 2018-11-14 11:18

import cvat.apps.engine.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20180917_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estimated_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='progress',
            field=cvat.apps.engine.fields.PercentField(default=0),
        ),
    ]
