# Generated by Django 2.1.7 on 2019-06-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_remove_task_flipped'),
        ('engine', '0020_auto_20190620_1235'),
    ]

    operations = [
    ]
