# Generated by Django 2.2.4 on 2019-08-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_auto_20190620_1235'),
        ('engine', '0021_auto_20190826_1827'),
    ]

    operations = [
    ]
