# Generated by Django 2.0.3 on 2018-11-18 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatssave',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
