# Generated by Django 2.1.7 on 2019-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190621_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatssave',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobstatssave',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
