# Generated by Django 2.0.3 on 2018-11-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20181118_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatssave',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobstatssave',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
