# Generated by Django 2.0.3 on 2018-12-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20181125_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatssave',
            name='system_tracked_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
