# Generated by Django 2.1.7 on 2019-06-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20190621_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatssave',
            name='system_tracked_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
